main/urls.py
from django.urls import path
from . import views
from .views import CartDeleteView

urlpatterns = [
    path('', views.index, name="home"),
    path('<int:pk>/', views.item),
    path('order/', views.order, name='order'),
    path('table/<int:pk>/order/', views.orders, name='orders'),
    # path('allorders/', views.allorders, name='allorders'),
    path('tables/', views.tables, name='tables'),
    path('prepare/<int:pk>', views.prepare, name='prepare'),
    path('on_prepare/<int:pk>', views.on_prepare, name='on_prepare'),
    path('on_orders/', views.on_orders, name="on_orders"),
    path('on_order/<slug:user>/', views.on_order, name='on_order'),
    path('on_allorders/', views.onallorders, name='on_allorders'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.get_cart_items, name='cart'),
    path('remove-from-cart/<int:pk>/', CartDeleteView.as_view(), name='remove-from-cart'),
    path('ordered/', views.order_item, name='ordered'),
    path('order_details/', views.order_details, name='order_details'),
    path('result-page/', views.schedule_queue, name="result-page"),

]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("main.urls", 'main'), namespace='main')),
    path('', include("account.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media/")
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    time = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Table(models.Model):
    table = models.CharField(max_length=50)

    def __str__(self):
        return self.table


class Order(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    status = models.CharField(max_length=100, default="pending...", blank=True)

    def __str__(self):
        return f"{self.item}"

    @property
    def price(self):
        price = self.item.price*self.quantity
        return price


class OnOrder(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=50)
    status = models.CharField(max_length=100, default="pending...", blank=True)

    def __str__(self):
        return f"{self.user}"

    @property
    def price(self):
        price = self.item.price*self.quantity
        return price


class CartItems(models.Model):
    ORDER_STATUS = (
        ('Active', 'Active'),
        ('Delivered', 'Delivered')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    ordered_date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='Active')
    delivery_date = models.DateField(default=timezone.now)

    class Meta:
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'

    def __str__(self):
        return self.item.name

main/forms.py
from django import forms
from .models import *


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('table', 'status',)


class OnOrderForm(forms.ModelForm):
    class Meta:
        model = OnOrder
        exclude = ('user', 'status', 'address', 'contact', )


class DetailForm(forms.ModelForm):
    class Meta:
        model = OnOrder
        fields = ('address', 'contact',)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Category, Item, Order, Table, CartItems
from .forms import *
from django.forms import formset_factory
import queue
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from datetime import datetime
from django.contrib import messages
from django.db.models import Sum
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def index(request):
    category = Category.objects.all()
    item = Item.objects.all()

    context = {
        'category': category,
        'item': item,
    }
    return render(request, "main/index.html", context)


def item(request, pk):
    category = Category.objects.all()
    item = Item.objects.filter(category_id=pk)
    return render(request, "main/item.html", {'item': item, 'category': category})


@user_passes_test(lambda u: u.is_staff, login_url='login')
def order(request):
    order1 = Order.objects.all().filter(table__table="t1")
    order2 = Order.objects.all().filter(table__table="t2")
    order3 = Order.objects.all().filter(table__table="t3")
    order4 = Order.objects.all().filter(table__table="t4")
    order5 = Order.objects.all().filter(table__table="t5")
    context = {
        "order1": order1,
        "order2": order2,
        "order3": order3,
        "order4": order4,
        "order5": order5
    }
    return render(request, "main/order.html", context)


process_list = []
result_list = []


@user_passes_test(lambda u: u.is_staff, login_url='login')
def orders(request, pk):
    table = Table.objects.filter(id=pk).first()
    orderformset = formset_factory(OrderForm)
    formset = orderformset(request.POST or None)
    if formset.is_valid():
        for form in formset:
            order = form.save(commit=False)
            order.table = table
            order.save()
        return redirect('/order')

    return render(request, 'main/orders.html', {'formset': formset, 'table': table})


@permission_required('is_superuser', raise_exception=True)
def onallorders(request):
    high = OnOrder.objects.all().filter(item__time__range=(0, 4)).exclude(status="prepared")
    medium = OnOrder.objects.all().filter(item__time__range=(5, 8)).exclude(status="prepared")
    low = OnOrder.objects.all().filter(item__time__range=(9, 13)).exclude(status="prepared")
    context = {
        'high': high,
        'medium': medium,
        'low': low,
    }
    return render(request, 'main/on_allorder.html', context)


@user_passes_test(lambda u: u.is_staff, login_url='login')
def tables(request):
    tables = Table.objects.all()
    return render(request, 'main/tables.html', {'tables': tables})


@permission_required('is_superuser', raise_exception=True)
def prepare(request, pk):
    order = get_object_or_404(Order, pk=pk)

    if request.method == 'POST':
        if order.status == 'pending...':
            order.status = "preparing..."
        else:
            order.status = "prepared"
        order.save()
        return redirect('/result-page')

    return render(request, 'main/prepare.html', {'order': order})


@login_required(login_url='login')
def on_orders(request):
    orderformset = formset_factory(OnOrderForm)
    formset = orderformset(request.POST or None)
    detail = DetailForm(request.POST or None)

    if detail.is_valid() and formset.is_valid():
        info = detail.save(commit=False)

        for form in formset:
            order = form.save(commit=False)
            order.user = request.user
            order.address = info.address
            order.contact = info.contact
            order.save()
        return redirect('/')

    return render(request, 'main/on_orders.html', {'formset': formset, 'detail': detail})


@login_required(login_url='login')
def on_order(request, user):
    order = OnOrder.objects.filter(user=request.user)
    return render(request, "main/on_order.html", {'order': order})


@permission_required('is_superuser', raise_exception=True)
def on_prepare(request, pk):
    order = get_object_or_404(OnOrder, pk=pk)

    if request.method == 'POST':
        if order.status == 'pending...':
            order.status = "preparing..."
        else:
            order.status = "prepared"
        order.save()
        return redirect('/on_allorders')

    return render(request, 'main/on_prepare.html', {'order': order})


@user_passes_test(lambda u: u.is_staff, login_url='login')
def delete(request, pk):
    order = Order.objects.all().filter(table_id=pk)

    if request.method == 'POST':
        order.delete()
        return redirect('/order')

    return render(request, 'main/delete.html', {'order': order})


@login_required(login_url='login')
def add_to_cart(request, pk):
    item = get_object_or_404(Item, id=pk)
    cart_item = CartItems.objects.create(
        item=item,
        user=request.user,
        ordered=False,
    )
    messages.info(request, "Added to Cart!!Continue Shopping!!")
    return redirect("main:cart")


@login_required
def get_cart_items(request):
    cart_items = CartItems.objects.filter(user=request.user, ordered=False)
    bill = cart_items.aggregate(Sum('item__price'))
    total = bill.get("item__price__sum")
    context = {
        'cart_items': cart_items,
        'total': total,
    }
    return render(request, 'main/cart.html', context)


class CartDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CartItems
    success_url = '/cart'

    def test_func(self):
        cart = self.get_object()
        if self.request.user == cart.user:
            return True
        return False


@login_required
def order_item(request):
    cart_items = CartItems.objects.filter(user=request.user, ordered=False)
    ordered_date = timezone.now()
    cart_items.update(ordered=True, ordered_date=ordered_date)
    messages.info(request, "Item Ordered")
    return redirect("main:order_details")


@login_required
def order_details(request):
    items = CartItems.objects.filter(user=request.user, ordered=True, status="Active").order_by('-ordered_date')
    cart_items = CartItems.objects.filter(user=request.user, ordered=True, status="Delivered").order_by('-ordered_date')
    bill = items.aggregate(Sum('item__price'))
    number = items.aggregate(Sum('quantity'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    context = {
        'items': items,
        'cart_items': cart_items,
        'total': total,
        'count': count,
    }
    return render(request, 'main/order_details.html', context)


class Process:
    def __init__(self, name, arrive_time, serve_time, id, table, quantity, status):
        self.name = name
        self.arrive_time = arrive_time
        self.serve_time = serve_time
        self.left_serve_time = serve_time
        self.finish_time = 0
        self.cycling_time = 0
        self.w_cycling_time = 0
        self.id = id
        self.table = table
        self.quantity = quantity
        self.status = status


# @permission_required('is_superuser', raise_exception=True)
# def allorders(request):
#     high = Order.objects.all().filter(item__time__range=(0, 4)).exclude(status="prepared")
#     medium = Order.objects.all().filter(item__time__range=(5, 8)).exclude(status="prepared")
#     low = Order.objects.all().filter(item__time__range=(9, 13)).exclude(status="prepared")
#     context = {
#         'high': high,
#         'medium': medium,
#         'low': low,
#     }
#     return render(request, 'main/allorder.html', context)


@permission_required('is_superuser', raise_exception=True)
def schedule_queue(request):
    result_list.clear()
    orders = Order.objects.all().exclude(status="prepared")
    for each in orders:
        new_process_name = each.item
        new_process_at = 0
        new_process_st = each.item.time
        table = each.table
        quantity = each.quantity
        status = each.status
        id = each.id

        new_process = Process(new_process_name, new_process_at, new_process_st, id, table, quantity, status)
        if new_process_name is not None:
            process_list.append(new_process)

    process_list0, process_list1, process_list2 = [], [], []
    for each in process_list:
        if each.serve_time <= 4:
            process_list0.append(each)
        elif each.serve_time <= 8:
            process_list1.append(each)
        else:
            process_list2.append(each)

    queue_list = []
    queue0 = Queue(0, process_list0)
    queue1 = Queue(1, process_list1)
    queue2 = Queue(2, process_list2)
    queue_list.append(queue0)
    queue_list.append(queue1)
    queue_list.append(queue2)

    mfq = Mulitlevelfeedbackqueue(queue_list, 8)
    mfq.scheduling()

    context = {
        "result_list": result_list
    }
    process_list.clear()
    return render(request, 'main/result_page.html', context)


class Queue:
    def __init__(self, level, process_list):
        self.level = level
        self.process_list = process_list
        self.q = 0

    def size(self):
        return len(self.process_list)

    def get(self, index):
        return self.process_list[index]

    def add(self, process):
        self.process_list.append(process)

    def delete(self, index):
        self.process_list.remove(self.process_list[index])


class RR:
    def __init__(self, process_list, q):
        self.process_list = process_list
        self.q = q

    def scheduling(self):
        process_list.sort(key=lambda x: x.arrive_time)  # according to .arrive_time Sort
        len_queue = len(self.process_list)  # The length of the process queue
        index = int(0)  # Indexes
        q = self.q  # Time slice
        running_time = int(0)  # Time already running

        # The scheduling loop
        while (True):
            if len_queue != 0:
                # The current process
                current_process = self.process_list[index % len_queue]

main/templates/main/allorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col-lg-4 col-md-4">
        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>table</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for high in high %}
            <tr class="table-success">
                <td>{{high.item.name}}</td>
                <td>{{high.quantity}}</td>
                <td>{{high.table}}</td>
                <td><a type="button" class="btn btn-danger" href="/prepare/{{high.id}}">{{high.status}}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-lg-4 col-md-4">
        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>table</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for medium in medium %}
            <tr class="table-warning">
                <td>{{medium.item.name}}</td>
                <td>{{medium.quantity}}</td>
                <td>{{medium.table}}</td>
                <td><a type="button" class="btn btn-danger" href="/prepare/{{medium.id}}">{{medium.status}}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-lg-4 col-md-4">
        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>table</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for low in low %}
            <tr class="table-danger">
                <td>{{low.item.name}}</td>
                <td>{{low.quantity}}</td>
                <td>{{low.table}}</td>
                <td><a type="button" class="btn btn-danger" href="/prepare/{{low.id}}">{{low.status}}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

</body>
</html>

main/templates/main/cart.html
{% extends "base.html" %}
{% block content %}
<div class="cart">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 mt-5">
                <h3 class="text-center">Your Cart</h3>
                {% if cart_items %}
                <div class="table-responsive">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">quantity</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for cart in cart_items %}
                        <tr>
                            <td>{{ cart.item.name }} <span class="badge badge-{{ cart.item.label_colour }}">{{ cart.item.labels }}</span></td>
                            <td>{{ cart.item.price }}</td>
                            <td>{{ cart.quantity }}</td>
                            <td><a class="btn btn-danger" href="{% url 'main:remove-from-cart' cart.id %}">Delete</a></td>
                        </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h4 class="text-center">Sorry, Your Cart is Empty....Please add Items!!!</h4>
                {% endif %}
            </div>
            <div class="col-sm-3 mt-5 mb-3">
                <div class="content-section">
                    <h3 class="text-center">Order Summary</h3>
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light text-center text-dark">Total: {{ total }}</li>
                        <li class="list-group-item list-group-item-light text-center text-dark"><a class="btn btn-primary" href="{% url 'main:ordered' %}">Proceed To Checkout</a></li>
                        <li class="list-group-item list-group-item-light text-center"><a class="btn btn-success" href="/">Continue Buying</a></li>
                      </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/cartitems_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Cart Item</legend>
                <h2>Are you sure you want to delete the post "{{ object.item.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-success" href="{% url 'main:cart' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/delete.html
{% extends 'base.html' %}

{% block content %}
<br>
<form method="post">
    {% csrf_token %}
    <h3>Are you sure you want to checkout for this table.</h3>
    <button type="submit" class="btn btn-danger">Yes,checkout</button>
</form>

{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    {% for item in item %}

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card bg-light" style="width: 18rem; margin: 20px;
box-shadow: 0 3px 3px rgba(0,0,0,0.01), 0 2px 2px rgba(0,0,0,0.24);">
            <img id="image" src="{{item.image.url}}" style="margin-bottom:-16px;">
            <hr>
            <div class="card-body">
                <h4 class="card-title" style="text-transform:capitalize;">{{item.name}}</h4>
                <h5>Price: Rs {{item.price}}</h5>
                {% if not user.is_staff and not user.is_superuser %}
                <a href="{% url 'main:add-to-cart' item.pk %}" class="btn btn-success btn-md my-0 p">Add to cart</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock %}

main/templates/main/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% for item in item %}

        <div class="col-lg-4 col-sm-6">
            <div class="card bg-light"
                 style="width: 18rem; margin:20px; box-shadow: 0 3px 3px rgba(0,0,0,0.01), 0 2px 2px rgba(0,0,0,0.24);">
                <img id="image" src="{{item.image.url}}" style="margin-bottom:-16px;">
                <hr>
                <div class="card-body">
                    <h4 class="card-title">{{item.name}}</h4>
                    <h5>Price: Rs {{item.price}}</h5>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

</body>
</html>

main/templates/main/on_allorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends "base.html" %}
{% block content %}

<div class="row">
        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>user</th>
                <th>contact</th>
                <th>address</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for high in high %}
            <tr class="table-success">
                <td>{{high.item.name}}</td>
                <td>{{high.quantity}}</td>
                <td>{{high.user}}</td>
                <td>{{high.contact}}</td>
                <td>{{high.address}}</td>
                <td><a type="button" class="btn btn-danger" href="/on_prepare/{{high.id}}">{{high.status}}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>



        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>user</th>
                <th>contact</th>
                <th>address</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for medium in medium %}
            <tr class="table-warning">
                <td>{{medium.item.name}}</td>
                <td>{{medium.quantity}}</td>
                <td>{{medium.user}}</td>
                <td>{{medium.contact}}</td>
                <td>{{medium.address}}</td>
                <td><a type="button" class="btn btn-danger" href="/on_prepare/{{medium.id}}">{{medium.status}}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <table align="center" class="table table-sm" style="max-width: 600px;max-height: 400px;">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>quantity</th>
                <th>user</th>
                <th>contact</th>
                <th>address</th>
                <th>status</th>
            </tr>
            </thead>
            <tbody>
            {% for low in low %}
            <tr class="table-danger">
                <td>{{low.item.name}}</td>
                <td>{{low.quantity}}</td>
                <td>{{low.user}}</td>
                <td>{{low.contact}}</td>
                <td>{{low.address}}</td>
                <td><a type="button" class="btn btn-danger" href="/on_prepare/{{low.id}}">{{low.status}}</a></td>
                </form>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

</body>
</html>

main/templates/main/on_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends "base.html" %}
{% block content %}

<table align="center" id="table" class="table table-sm" style="max-width: 600px;max-height: 400px;">
		<thead class="thead-dark">
			<tr>
			<th>Name</th>
			<th>contact</th>
            <th>address</th>
			<th>unit Price</th>
			<th>quantity</th>
			<th>price</th>
			<th>status</th>
			</tr>
		</thead>
		<tbody>
        {% for order in order %}
			<tr class="table-active">
			<td>{{order.item.name}}</td>
			<td>{{order.contact}}</td>
            <td>{{order.address}}</td>
			<td>{{order.item.price}}</td>
			<td>{{order.quantity}}</td>
            <td class="price">{{order.price}}</td>
			<td>{{order.status}}</td>
			</tr>
		{% endfor %}
			<tr class="table-success">
			<td></td>
			<td></td>
            <td></td>
			<td></td>
			<td>Total</td>
            <td class="total"></td>
			</tr>
		</tbody>
</table>
	<script type="text/javascript">
		var total = 0;
		$("#table tr td.price").each(function(){
			total += parseInt($(this).text());
		});
		$("#table tr td.total").text(total);
	</script>
{% endblock %}
</body>
</html>

main/templates/main/on_prepare.html
{% extends 'base.html' %}

{% block content %}
<br>
<form method="post">
    {% csrf_token %}
    <h3>Are you sure you want to prepare the food "{{order.item}}"</h3>
    <button type="submit" class="btn btn-danger">Yes,prepare</button>
</form>

{% endblock %}

main/templates/main/order_details.html
{% extends "base.html" %}
{% block content %}
<div class="cart">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 mt-5">
                <h3 class="text-center" style="color:red;">Active Orders</h3>
                {% if items %}
                <h4 class="text-center">Total Bill Amount: {{total}} for {{ count }} Orders.</h4>
                <h6 class="text-center">Please Pay Either via ATM or Credit Card or Cash on Delivery!</h6>
                <div class="table-responsive">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th scope="col">Ordered</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Order Status</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for item_active in items %}
                        <tr>
                            <td>{{ item_active.ordered_date }}</td>
                            <td>{{ item_active.item.name }} <span class="badge badge-{{ item_active.item.label_colour }}">{{ item_active.item.labels }}</span></td>
                            <td>{{ item_active.item.price }}</td>
                            <td>{{ item_active.status }}</td>
                        </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h4 class="text-center">Sorry, you have not ordered any item yet!!!</h4>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 mt-5">
                <h3 class="text-center" style="color:green;">Delivered Orders</h3>
                {% if cart_items %}
                <div class="table-responsive">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th scope="col">Ordered</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Order Status</th>
                            <th scope="col">Delivery Date</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for cart in cart_items %}
                        <tr>
                            <td>{{ cart.ordered_date }}</td>
                            <td>{{ cart.item.name }} <span class="badge badge-{{ cart.item.label_colour }}">{{ cart.item.labels }}</span></td>
                            <td>{{ cart.item.price }}</td>
                            <td>{{ cart.status }}</td>
                            <td>{{ cart.delivery_date }}</td>
                        </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h4 class="text-center">Sorry, you have not ordered any item yet!!!</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends 'base.html' %}
{% block content %}

<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form}}
    <div id="form_set" class="jumbotron" style="padding:30px;">
    <b>Table: {{table}} </b>
        <hr>
    {% for form in formset.forms %}
    <table class="no_error">
    {{form}}
    </table>
    <hr>

    {% endfor %}
    </div>

    <input type="button" value="Add More" id="add_more">
    <div id="empty_form" style="display:none">
        <table class="no_error">
            {{formset.empty_form}}
            <hr>
        </table>
    </div>
    <div class="footer" style="float:right;">
        <button type="submit" class="btn btn-success">confirm</button>
    </div>
</form>

<script>
     $('#add_more').click(function() {
        var form_idx = $('#id_form-TOTAL_FORMS').val();
	$('#form_set').append($('#empty_form').html().replace  (/__prefix__/g, form_idx));
	$('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
});
</script>

{% endblock %}

</body>
</html>

main/templates/main/tables.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for table in tables %}

        <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <a class="card-block stretched-link text-decoration-none" href="/table/{{table.id}}/order">
                        <h3>Table: {{table}}</h3>
                    </a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}